'use strict';

const conceptRelationSchema = require('./concept-relation-schema');
const {
  BOUNDARY_PROOF_FIELDS,
  BOUNDARY_PROOF_REQUIRED_CLASSIFICATIONS,
  getRequiredBoundaryProofComparisons,
  validateBoundaryProof,
  validateBoundaryProofCatalog,
  validateBoundaryProofRequirements,
} = require('./concept-boundary-proof');
const {
  assertConstraintContractTargetsWithinLiveKernel,
  assertLiveConceptConstraintContractIntegration,
  buildConstraintContractSummary,
  CONSTRAINT_CONTRACT_RESOLUTION_VALUES,
  evaluateConstraintContractCase,
  evaluateLawConstraintCase,
  loadGovernanceDomainLock,
  validateConstraintContractShape,
  validateGovernanceDomainLock,
} = require('./constraint-contract');
const {
  BLOCKING_OVERLAP_ADMISSION_VALUES,
  OVERLAP_ADMISSION_VALUES,
  assertConceptEligibleForLiveAdmission,
  assertLiveConceptOverlapAdmissions,
  evaluateConceptOverlapAdmission,
} = require('./concept-overlap-admission-gate');
const {
  ADJACENCY_CLASSIFICATIONS,
  BLOCKING_CLASSIFICATIONS,
  buildConceptOverlapInspectionReport,
  getConceptOverlapReport,
  loadInspectableConceptSet,
} = require('./concept-overlap-report-service');
const {
  BOUNDARY_CHANGE_APPROVAL_FIELDS,
  assertStoredConceptRelationshipSnapshotAuthority,
  buildCurrentConceptRelationshipSnapshot,
  evaluateConceptRelationshipSnapshotDrift,
  findMatchingBoundaryChangeApproval,
  loadBoundaryChangeApprovalRegistry,
  loadStoredConceptRelationshipSnapshot,
  writeConceptRelationshipSnapshot,
} = require('./concept-overlap-snapshot');
const {
  COMPARISON_CLASSIFICATIONS,
  COMPARISON_FIELD_ORDER,
  ROLE_DIFFERENTIATION_FIELDS,
  buildLiveConceptProfiles,
  compareConceptProfiles,
  compareProfileAgainstLiveConcepts,
} = require('./concept-profile-comparator');
const {
  STRUCTURAL_PROFILE_FIELDS,
  STRUCTURAL_PROFILE_SEED_FIELDS,
  normalizeConceptToProfile,
  validateConceptStructuralProfile,
  validateConceptStructuralProfileSeed,
} = require('./concept-structural-profile');
const { loadAuthoredRelationPackets } = require('./concept-relation-loader');
const {
  deriveConceptRuntimeGovernanceState,
  getConceptRuntimeGovernanceState,
  loadConceptValidationSnapshot,
} = require('./concept-validation-state-loader');
const {
  getPreAdmissionContractPath,
  loadPreAdmissionContractPathRegistry,
} = require('./pre-admission-contract-path');
const {
  RESPONSE_TYPE_TO_RUNTIME_RESOLUTION_STATE,
  RUNTIME_RESOLUTION_STATES,
  assertSingleRuntimeResolutionState,
  deriveRuntimeResolutionStateFromResponse,
} = require('./runtime-resolution-state');
const {
  STRUCTURAL_FAILURE_KINDS,
  classifyConstraintContractCollision,
  classifyConstraintContractFailure,
} = require('./structural-failure-layer');
const { buildConceptDetail } = require('./concept-detail-service');
const {
  getConceptById,
  loadConceptSet,
  RESOLUTION_STATUS_VALUES,
} = require('./concept-loader');
const {
  ALLOWED_ADMISSION_VALUES,
  ALLOWED_VALIDATION_SOURCES,
  clearConceptReviewStateCache,
  getConceptReviewState,
  loadConceptReviewStateRegistry,
  reviewStateDirectoryPath,
  validateConceptReviewStateRecord,
} = require('./concept-review-state-loader');
const { evaluateBlockedConceptAdmission } = require('./blocked-concept-admission');
const {
  CONCEPT_UNLOCK_OVERRIDE_TEMPLATE,
  INVALID_OVERRIDE_REASON,
  OVERRIDE_DISABLED_REASON,
  OVERRIDABLE_CONCEPT_ID,
  OVERRIDE_ACTOR_ROLE,
  OVERRIDE_APPROVAL_TOKEN,
  OVERRIDE_REASON,
  OVERRIDE_SCOPE,
  applyOverride,
  clearOverrideAttemptLog,
  getOverrideAttemptLog,
  logOverrideAttempt,
  validateOverride,
} = require('./concept-unlock-override');
const conceptStructureSchema = require('./concept-structure-schema');
const { resolveConceptQuery } = require('./resolver');

module.exports = {
  ALLOWED_ADMISSION_VALUES,
  ALLOWED_VALIDATION_SOURCES,
  ADJACENCY_CLASSIFICATIONS,
  BOUNDARY_CHANGE_APPROVAL_FIELDS,
  BLOCKING_OVERLAP_ADMISSION_VALUES,
  BLOCKING_CLASSIFICATIONS,
  BOUNDARY_PROOF_FIELDS,
  BOUNDARY_PROOF_REQUIRED_CLASSIFICATIONS,
  COMPARISON_CLASSIFICATIONS,
  COMPARISON_FIELD_ORDER,
  CONSTRAINT_CONTRACT_RESOLUTION_VALUES,
  CONCEPT_UNLOCK_OVERRIDE_TEMPLATE,
  INVALID_OVERRIDE_REASON,
  OVERRIDE_DISABLED_REASON,
  OVERRIDABLE_CONCEPT_ID,
  OVERRIDE_ACTOR_ROLE,
  OVERRIDE_APPROVAL_TOKEN,
  OVERRIDE_REASON,
  OVERRIDE_SCOPE,
  RESPONSE_TYPE_TO_RUNTIME_RESOLUTION_STATE,
  ROLE_DIFFERENTIATION_FIELDS,
  RUNTIME_RESOLUTION_STATES,
  RESOLUTION_STATUS_VALUES,
  STRUCTURAL_PROFILE_FIELDS,
  STRUCTURAL_PROFILE_SEED_FIELDS,
  STRUCTURAL_FAILURE_KINDS,
  applyOverride,
  assertConstraintContractTargetsWithinLiveKernel,
  assertConceptEligibleForLiveAdmission,
  assertLiveConceptConstraintContractIntegration,
  assertLiveConceptOverlapAdmissions,
  assertSingleRuntimeResolutionState,
  assertStoredConceptRelationshipSnapshotAuthority,
  buildCurrentConceptRelationshipSnapshot,
  buildConstraintContractSummary,
  buildConceptOverlapInspectionReport,
  buildLiveConceptProfiles,
  buildConceptDetail,
  classifyConstraintContractCollision,
  classifyConstraintContractFailure,
  clearConceptReviewStateCache,
  clearOverrideAttemptLog,
  evaluateBlockedConceptAdmission,
  evaluateConstraintContractCase,
  evaluateConceptRelationshipSnapshotDrift,
  deriveConceptRuntimeGovernanceState,
  deriveRuntimeResolutionStateFromResponse,
  evaluateLawConstraintCase,
  findMatchingBoundaryChangeApproval,
  getConceptById,
  getConceptReviewState,
  getConceptRuntimeGovernanceState,
  getPreAdmissionContractPath,
  loadBoundaryChangeApprovalRegistry,
  getOverrideAttemptLog,
  loadConceptSet,
  loadStoredConceptRelationshipSnapshot,
  loadConceptReviewStateRegistry,
  loadConceptValidationSnapshot,
  loadGovernanceDomainLock,
  loadPreAdmissionContractPathRegistry,
  loadAuthoredRelationPackets,
  logOverrideAttempt,
  compareConceptProfiles,
  compareProfileAgainstLiveConcepts,
  conceptRelationSchema,
  conceptStructureSchema,
  evaluateConceptOverlapAdmission,
  getRequiredBoundaryProofComparisons,
  getConceptOverlapReport,
  normalizeConceptToProfile,
  OVERLAP_ADMISSION_VALUES,
  loadInspectableConceptSet,
  reviewStateDirectoryPath,
  resolveConceptQuery,
  validateConstraintContractShape,
  validateBoundaryProof,
  validateBoundaryProofCatalog,
  validateBoundaryProofRequirements,
  validateGovernanceDomainLock,
  validateConceptStructuralProfile,
  validateConceptStructuralProfileSeed,
  validateConceptReviewStateRecord,
  validateOverride,
  writeConceptRelationshipSnapshot,
};
