'use strict';

const {
  ZEE_INTERNAL_ENGINE_COMPARATOR_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_COMPARATOR_POLICY,
  ZEE_INTERNAL_ENGINE_EXTRACTOR_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY,
  ZEE_INTERNAL_ENGINE_INFERENCE_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_INFERENCE_POLICY,
  ZEE_INTERNAL_ENGINE_INPUT_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_INPUT_POLICY,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_MEASUREMENT_POLICY,
  ZEE_INTERNAL_ENGINE_PNG_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_PNG_POLICY,
  ZEE_INTERNAL_ENGINE_POLICY_MANIFEST: ZEE_INTERNAL_ENGINE_BASE_POLICY_MANIFEST,
  ZEE_INTERNAL_ENGINE_POLICY_MANIFEST_VERSION,
  ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  ZEE_INTERNAL_ENGINE_STABILITY_POLICY: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY,
} = require('./policy-manifest');
const {
  ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS,
} = require('./phase-schemas');

const ZEE_INTERNAL_ENGINE_NAME = 'ZEE Internal Engine';
const ZEE_INTERNAL_ENGINE_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_LAYER = 'Observed';

const ZEE_INTERNAL_ENGINE_MAX_FRAMES = ZEE_INTERNAL_ENGINE_MANIFEST_INPUT_POLICY.maxFrames;
const ZEE_INTERNAL_ENGINE_MAX_FRAME_BYTES = ZEE_INTERNAL_ENGINE_MANIFEST_INPUT_POLICY.maxFrameBytes;
const ZEE_INTERNAL_ENGINE_DEFAULT_TILE_SIZE = ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY.defaultTileSize;
const ZEE_INTERNAL_ENGINE_DEFAULT_EDGE_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY.defaultEdgeThreshold;
const ZEE_INTERNAL_ENGINE_DEFAULT_MAX_DOMINANT_COLORS = ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY.defaultMaxDominantColors;
const ZEE_INTERNAL_ENGINE_DEFAULT_MAX_REGION_CANDIDATES = ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY.defaultMaxRegionCandidates;
const ZEE_INTERNAL_ENGINE_STABILITY_LAYER = 'Signal Stability';
const ZEE_INTERNAL_ENGINE_STABILITY_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_STABILITY_MIN_SUPPORT = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.minSupport;
const ZEE_INTERNAL_ENGINE_STABILITY_MATCH_SCORE_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.matchScoreThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_DISTANCE_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorDistanceThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_RATIO_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorRatioThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_CENTER_SHIFT_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.regionCenterShiftThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_SIZE_SHIFT_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.regionSizeShiftThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_AREA_SHIFT_THRESHOLD = ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.regionAreaShiftThreshold;
const ZEE_INTERNAL_ENGINE_STABILITY_KIND_ORDER = Object.freeze([
  ...ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.kindOrder,
]);
const ZEE_INTERNAL_ENGINE_MEASUREMENT_LAYER = 'Measured';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NUMERIC_PRECISION = ZEE_INTERNAL_ENGINE_MANIFEST_MEASUREMENT_POLICY.numericPrecision;
const ZEE_INTERNAL_ENGINE_MEASUREMENT_SUPPORTED_SIGNAL_KINDS = Object.freeze([
  ...ZEE_INTERNAL_ENGINE_MANIFEST_MEASUREMENT_POLICY.supportedSignalKinds,
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_LAYER = 'Inference Gate';
const ZEE_INTERNAL_ENGINE_INFERENCE_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT = ZEE_INTERNAL_ENGINE_MANIFEST_INFERENCE_POLICY.minSupport;
const ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORTED_CLAIM_TYPES = Object.freeze([
  'multi_signal_structural_similarity',
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_REJECTED_CLAIM_TYPES = Object.freeze([
  'single_signal_inference',
  'cross_kind_support_required',
  'identity_inference',
  'intent_inference',
  'location_certainty',
  'truth_claim',
  'meaning_reconstruction',
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_UNKNOWN_TYPES = Object.freeze([
  'bounded_support_scope_unknown',
]);

const ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS = Object.freeze([
  ...ZEE_INTERNAL_ENGINE_MANIFEST_INPUT_POLICY.supportedFormats,
]);
const ZEE_INTERNAL_ENGINE_INPUT_POLICY = Object.freeze({
  ...ZEE_INTERNAL_ENGINE_MANIFEST_INPUT_POLICY,
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});

const ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION = ZEE_INTERNAL_ENGINE_POLICY_VERSION;
const ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY = Object.freeze({
  inference: Object.freeze({
    refused: 'REFUSED',
    supported: 'SUPPORTED',
    unknown: 'UNKNOWN',
    unsupported: 'UNSUPPORTED',
  }),
  measurement: Object.freeze({
    discarded: 'DISCARDED',
    measured: 'MEASURED',
  }),
  signalStability: Object.freeze({
    discarded: 'DISCARDED',
    stable: 'STABLE',
  }),
});
const ZEE_INTERNAL_ENGINE_COMPARATOR_POLICY = ZEE_INTERNAL_ENGINE_MANIFEST_COMPARATOR_POLICY;
const ZEE_INTERNAL_ENGINE_PNG_POLICY = Object.freeze({
  ...ZEE_INTERNAL_ENGINE_MANIFEST_PNG_POLICY,
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});
const ZEE_INTERNAL_ENGINE_EXTRACTOR_POLICY = Object.freeze({
  ...ZEE_INTERNAL_ENGINE_MANIFEST_EXTRACTOR_POLICY,
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});

const ZEE_INTERNAL_ENGINE_INPUT_CONTRACT = Object.freeze({
  frames: 'Array<string | Buffer | { path?: string, buffer?: Buffer, label?: string, sourceId?: string, artifactId?: string }>',
  supportedFormats: [...ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS],
  options: 'Optional deterministic tuning values: tileSize, edgeThreshold, maxDominantColors, maxRegionCandidates.',
});

const ZEE_INTERNAL_ENGINE_ERROR_CODES = Object.freeze({
  INVALID_INPUT: 'invalid_zee_input',
  INVALID_IMAGE: 'invalid_zee_image',
});

const ZEE_INTERNAL_ENGINE_OBSERVED_ONLY_NOTE =
  'Observed-only pipeline: pixel-grounded features only; no inference, text guessing, object naming, identity reading, or truth claims.';

const ZEE_INTERNAL_ENGINE_NON_OPERATIONAL_NOTE =
  'Non-operational engine module: local and isolated, not connected to ChatPDM runtime.';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NOTE =
  'Measured layer: only stable signals are normalized into deterministic numeric or categorical measurements.';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NON_MEASURABLE_NOTE =
  'Unsupported stable signals are discarded with explicit diagnostics instead of being interpreted.';
const ZEE_INTERNAL_ENGINE_INFERENCE_NOTE =
  'Inference gate: only bounded structural similarity claims are allowed, and only when at least two measured signals satisfy the declared cross-kind support policy.';
const ZEE_INTERNAL_ENGINE_INFERENCE_NON_AUTHORITATIVE_NOTE =
  'All unsupported claims are explicitly rejected; the gate does not produce identity, intent, location certainty, or truth claims.';

const ZEE_INTERNAL_ENGINE_STABILITY_POLICY = Object.freeze({
  dominantColorScoreWeights: Object.freeze({
    colorDistanceScale: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorScoreWeights.colorDistanceScale,
    colorDistanceWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorScoreWeights.colorDistanceWeight,
    rankDistanceCap: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorScoreWeights.rankDistanceCap,
    rankDistanceWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorScoreWeights.rankDistanceWeight,
    ratioWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.dominantColorScoreWeights.ratioWeight,
  }),
  dominantColorDistanceThreshold: ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_DISTANCE_THRESHOLD,
  dominantColorRatioThreshold: ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_RATIO_THRESHOLD,
  kindOrder: Object.freeze([...ZEE_INTERNAL_ENGINE_STABILITY_KIND_ORDER]),
  matchScoreThreshold: ZEE_INTERNAL_ENGINE_STABILITY_MATCH_SCORE_THRESHOLD,
  minSupport: ZEE_INTERNAL_ENGINE_STABILITY_MIN_SUPPORT,
  resultTaxonomyVersion: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  regionAreaShiftThreshold: ZEE_INTERNAL_ENGINE_STABILITY_REGION_AREA_SHIFT_THRESHOLD,
  regionCenterShiftThreshold: ZEE_INTERNAL_ENGINE_STABILITY_REGION_CENTER_SHIFT_THRESHOLD,
  regionSizeShiftThreshold: ZEE_INTERNAL_ENGINE_STABILITY_REGION_SIZE_SHIFT_THRESHOLD,
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  roundingPrecision: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.defaultRoundingPrecision,
  visibleRegionScoreWeights: Object.freeze({
    areaShiftWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.visibleRegionScoreWeights.areaShiftWeight,
    centerShiftWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.visibleRegionScoreWeights.centerShiftWeight,
    geometryMismatchPenalty: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.visibleRegionScoreWeights.geometryMismatchPenalty,
    heightShiftWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.visibleRegionScoreWeights.heightShiftWeight,
    widthShiftWeight: ZEE_INTERNAL_ENGINE_MANIFEST_STABILITY_POLICY.visibleRegionScoreWeights.widthShiftWeight,
  }),
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});
const ZEE_INTERNAL_ENGINE_MEASUREMENT_POLICY = Object.freeze({
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  numericPrecision: ZEE_INTERNAL_ENGINE_MEASUREMENT_NUMERIC_PRECISION,
  supportedSignalKinds: Object.freeze([...ZEE_INTERNAL_ENGINE_MEASUREMENT_SUPPORTED_SIGNAL_KINDS]),
  resultTaxonomyVersion: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});
const ZEE_INTERNAL_ENGINE_INFERENCE_POLICY = Object.freeze({
  policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  minimumDistinctMeasurementTypes: 2,
  minimumDistinctSignalKinds: 2,
  minimumMeasuredSignals: ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
  minDistinctMeasurementTypes: 2,
  minDistinctSignalKinds: 2,
  minSupport: ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
  rejectedClaimTypes: Object.freeze([...ZEE_INTERNAL_ENGINE_INFERENCE_REJECTED_CLAIM_TYPES]),
  resultTaxonomyVersion: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  supportedClaimTypes: Object.freeze([...ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORTED_CLAIM_TYPES]),
  supportPolicyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  requireDistinctStableSignalIds: true,
  supportPolicy: Object.freeze({
    minimumDistinctMeasurementTypes: 2,
    minimumDistinctSignalKinds: 2,
    minimumMeasuredSignals: ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
    minDistinctMeasurementTypes: 2,
    minDistinctSignalKinds: 2,
    minMeasuredSignals: ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
    policyVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
    requiresCrossKindDiversity: true,
    requiresDistinctMeasurementTypes: true,
    requireDistinctStableSignalIds: true,
    requiresDistinctStableSignalIds: true,
    supportRule: 'cross_kind_distinct_multi_signal',
    supportRuleVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
    supportType: 'bounded_structural_similarity',
    supportTypeVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
    version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  }),
  unknownTypes: Object.freeze([...ZEE_INTERNAL_ENGINE_INFERENCE_UNKNOWN_TYPES]),
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});
const ZEE_INTERNAL_ENGINE_TRACE_CONTRACT = Object.freeze({
  canonicalReplayArtifactSchemaVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  canonicalTraceSchemaVersion: ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  canonicalTraceMetadataSchemaVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  inferenceGateSchemaVersion: ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  measurementSchemaVersion: ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  observedFrameSchemaVersion: ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  replayManifestSchemaVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  signalStabilitySchemaVersion: ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  observedFrameArtifactSchemaVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  phaseOutcomeTaxonomySchemaVersion: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  supportPolicySchemaVersion: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});
const ZEE_INTERNAL_ENGINE_OBSERVED_FRAME_SCHEMA = ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS.observedFrame;
const ZEE_INTERNAL_ENGINE_SIGNAL_STABILITY_SCHEMA = ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS.signalStability;
const ZEE_INTERNAL_ENGINE_MEASUREMENT_SCHEMA = ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS.measurement;
const ZEE_INTERNAL_ENGINE_INFERENCE_GATE_SCHEMA = ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS.inferenceGate;
const ZEE_INTERNAL_ENGINE_CANONICAL_TRACE_SCHEMA = ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS.canonicalTrace;
const ZEE_INTERNAL_ENGINE_POLICY_MANIFEST = Object.freeze({
  ...ZEE_INTERNAL_ENGINE_BASE_POLICY_MANIFEST,
  resultTaxonomy: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY,
  resultTaxonomyVersion: ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  supportPolicy: ZEE_INTERNAL_ENGINE_INFERENCE_POLICY.supportPolicy,
  trace: ZEE_INTERNAL_ENGINE_TRACE_CONTRACT,
  version: ZEE_INTERNAL_ENGINE_POLICY_VERSION,
});

module.exports = {
  ZEE_INTERNAL_ENGINE_DEFAULT_EDGE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_DEFAULT_MAX_DOMINANT_COLORS,
  ZEE_INTERNAL_ENGINE_DEFAULT_MAX_REGION_CANDIDATES,
  ZEE_INTERNAL_ENGINE_DEFAULT_TILE_SIZE,
  ZEE_INTERNAL_ENGINE_ERROR_CODES,
  ZEE_INTERNAL_ENGINE_INPUT_CONTRACT,
  ZEE_INTERNAL_ENGINE_INPUT_POLICY,
  ZEE_INTERNAL_ENGINE_LAYER,
  ZEE_INTERNAL_ENGINE_MAX_FRAME_BYTES,
  ZEE_INTERNAL_ENGINE_MAX_FRAMES,
  ZEE_INTERNAL_ENGINE_NAME,
  ZEE_INTERNAL_ENGINE_CANONICAL_TRACE_SCHEMA,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_LAYER,
  ZEE_INTERNAL_ENGINE_INFERENCE_LAYER,
  ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
  ZEE_INTERNAL_ENGINE_INFERENCE_NON_AUTHORITATIVE_NOTE,
  ZEE_INTERNAL_ENGINE_INFERENCE_NOTE,
  ZEE_INTERNAL_ENGINE_INFERENCE_POLICY,
  ZEE_INTERNAL_ENGINE_INFERENCE_REJECTED_CLAIM_TYPES,
  ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORTED_CLAIM_TYPES,
  ZEE_INTERNAL_ENGINE_INFERENCE_UNKNOWN_TYPES,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NON_MEASURABLE_NOTE,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NOTE,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_POLICY,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NUMERIC_PRECISION,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_SUPPORTED_SIGNAL_KINDS,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_VERSION,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_SCHEMA,
  ZEE_INTERNAL_ENGINE_INFERENCE_VERSION,
  ZEE_INTERNAL_ENGINE_INFERENCE_GATE_SCHEMA,
  ZEE_INTERNAL_ENGINE_NON_OPERATIONAL_NOTE,
  ZEE_INTERNAL_ENGINE_OBSERVED_ONLY_NOTE,
  ZEE_INTERNAL_ENGINE_OBSERVED_FRAME_SCHEMA,
  ZEE_INTERNAL_ENGINE_POLICY_MANIFEST,
  ZEE_INTERNAL_ENGINE_POLICY_MANIFEST_VERSION,
  ZEE_INTERNAL_ENGINE_POLICY_VERSION,
  ZEE_INTERNAL_ENGINE_COMPARATOR_POLICY,
  ZEE_INTERNAL_ENGINE_PHASE_SCHEMA_VERSION,
  ZEE_INTERNAL_ENGINE_PHASE_SCHEMAS,
  ZEE_INTERNAL_ENGINE_PNG_POLICY,
  ZEE_INTERNAL_ENGINE_EXTRACTOR_POLICY,
  ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY,
  ZEE_INTERNAL_ENGINE_RESULT_TAXONOMY_VERSION,
  ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORT_POLICY: ZEE_INTERNAL_ENGINE_INFERENCE_POLICY.supportPolicy,
  ZEE_INTERNAL_ENGINE_SIGNAL_STABILITY_SCHEMA,
  ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_DISTANCE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_RATIO_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_KIND_ORDER,
  ZEE_INTERNAL_ENGINE_STABILITY_LAYER,
  ZEE_INTERNAL_ENGINE_STABILITY_POLICY,
  ZEE_INTERNAL_ENGINE_STABILITY_MATCH_SCORE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_MIN_SUPPORT,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_AREA_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_CENTER_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_SIZE_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_VERSION,
  ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS,
  ZEE_INTERNAL_ENGINE_TRACE_CONTRACT,
  ZEE_INTERNAL_ENGINE_VERSION,
};
