'use strict';

const ZEE_INTERNAL_ENGINE_NAME = 'ZEE Internal Engine';
const ZEE_INTERNAL_ENGINE_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_LAYER = 'Observed';

const ZEE_INTERNAL_ENGINE_MAX_FRAMES = 8;
const ZEE_INTERNAL_ENGINE_MAX_FRAME_BYTES = 25 * 1024 * 1024;
const ZEE_INTERNAL_ENGINE_DEFAULT_TILE_SIZE = 32;
const ZEE_INTERNAL_ENGINE_DEFAULT_EDGE_THRESHOLD = 24;
const ZEE_INTERNAL_ENGINE_DEFAULT_MAX_DOMINANT_COLORS = 8;
const ZEE_INTERNAL_ENGINE_DEFAULT_MAX_REGION_CANDIDATES = 12;
const ZEE_INTERNAL_ENGINE_STABILITY_LAYER = 'Signal Stability';
const ZEE_INTERNAL_ENGINE_STABILITY_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_STABILITY_MIN_SUPPORT = 2;
const ZEE_INTERNAL_ENGINE_STABILITY_MATCH_SCORE_THRESHOLD = 0.72;
const ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_DISTANCE_THRESHOLD = 48;
const ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_RATIO_THRESHOLD = 0.18;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_CENTER_SHIFT_THRESHOLD = 0.14;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_SIZE_SHIFT_THRESHOLD = 0.38;
const ZEE_INTERNAL_ENGINE_STABILITY_REGION_AREA_SHIFT_THRESHOLD = 0.2;
const ZEE_INTERNAL_ENGINE_STABILITY_KIND_ORDER = Object.freeze([
  'dominant_color',
  'visible_region',
]);
const ZEE_INTERNAL_ENGINE_MEASUREMENT_LAYER = 'Measured';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NUMERIC_PRECISION = 6;
const ZEE_INTERNAL_ENGINE_MEASUREMENT_SUPPORTED_SIGNAL_KINDS = Object.freeze([
  'dominant_color',
  'visible_region',
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_LAYER = 'Inference Gate';
const ZEE_INTERNAL_ENGINE_INFERENCE_VERSION = 'v1';
const ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT = 2;
const ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORTED_CLAIM_TYPES = Object.freeze([
  'multi_signal_structural_similarity',
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_REJECTED_CLAIM_TYPES = Object.freeze([
  'single_signal_inference',
  'identity_inference',
  'intent_inference',
  'location_certainty',
  'truth_claim',
  'meaning_reconstruction',
]);
const ZEE_INTERNAL_ENGINE_INFERENCE_UNKNOWN_TYPES = Object.freeze([
  'semantic_reconstruction_unknown',
]);

const ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS = Object.freeze(['png']);

const ZEE_INTERNAL_ENGINE_INPUT_CONTRACT = Object.freeze({
  frames: 'Array<string | Buffer | { path?: string, buffer?: Buffer, label?: string, sourceId?: string }>',
  supportedFormats: [...ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS],
  options: 'Optional deterministic tuning values: tileSize, edgeThreshold, maxDominantColors, maxRegionCandidates.',
});

const ZEE_INTERNAL_ENGINE_ERROR_CODES = Object.freeze({
  INVALID_INPUT: 'invalid_zee_input',
  INVALID_IMAGE: 'invalid_zee_image',
});

const ZEE_INTERNAL_ENGINE_OBSERVED_ONLY_NOTE =
  'Observed-only pipeline: pixel-grounded features only; no inference, text guessing, object naming, identity reading, or truth claims.';

const ZEE_INTERNAL_ENGINE_NON_OPERATIONAL_NOTE =
  'Non-operational engine module: local and isolated, not connected to ChatPDM runtime.';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NOTE =
  'Measured layer: only stable signals are normalized into deterministic numeric or categorical measurements.';
const ZEE_INTERNAL_ENGINE_MEASUREMENT_NON_MEASURABLE_NOTE =
  'Unsupported stable signals are discarded with explicit diagnostics instead of being interpreted.';
const ZEE_INTERNAL_ENGINE_INFERENCE_NOTE =
  'Inference gate: only bounded structural similarity claims are allowed, and only when at least two independent measured signals are present.';
const ZEE_INTERNAL_ENGINE_INFERENCE_NON_AUTHORITATIVE_NOTE =
  'All unsupported claims are explicitly rejected; the gate does not produce identity, intent, location certainty, or truth claims.';

module.exports = {
  ZEE_INTERNAL_ENGINE_DEFAULT_EDGE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_DEFAULT_MAX_DOMINANT_COLORS,
  ZEE_INTERNAL_ENGINE_DEFAULT_MAX_REGION_CANDIDATES,
  ZEE_INTERNAL_ENGINE_DEFAULT_TILE_SIZE,
  ZEE_INTERNAL_ENGINE_ERROR_CODES,
  ZEE_INTERNAL_ENGINE_INPUT_CONTRACT,
  ZEE_INTERNAL_ENGINE_LAYER,
  ZEE_INTERNAL_ENGINE_MAX_FRAME_BYTES,
  ZEE_INTERNAL_ENGINE_MAX_FRAMES,
  ZEE_INTERNAL_ENGINE_NAME,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_LAYER,
  ZEE_INTERNAL_ENGINE_INFERENCE_LAYER,
  ZEE_INTERNAL_ENGINE_INFERENCE_MIN_SUPPORT,
  ZEE_INTERNAL_ENGINE_INFERENCE_NON_AUTHORITATIVE_NOTE,
  ZEE_INTERNAL_ENGINE_INFERENCE_NOTE,
  ZEE_INTERNAL_ENGINE_INFERENCE_REJECTED_CLAIM_TYPES,
  ZEE_INTERNAL_ENGINE_INFERENCE_SUPPORTED_CLAIM_TYPES,
  ZEE_INTERNAL_ENGINE_INFERENCE_UNKNOWN_TYPES,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NON_MEASURABLE_NOTE,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NOTE,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_NUMERIC_PRECISION,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_SUPPORTED_SIGNAL_KINDS,
  ZEE_INTERNAL_ENGINE_MEASUREMENT_VERSION,
  ZEE_INTERNAL_ENGINE_INFERENCE_VERSION,
  ZEE_INTERNAL_ENGINE_NON_OPERATIONAL_NOTE,
  ZEE_INTERNAL_ENGINE_OBSERVED_ONLY_NOTE,
  ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_DISTANCE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_DOMINANT_COLOR_RATIO_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_KIND_ORDER,
  ZEE_INTERNAL_ENGINE_STABILITY_LAYER,
  ZEE_INTERNAL_ENGINE_STABILITY_MATCH_SCORE_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_MIN_SUPPORT,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_AREA_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_CENTER_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_REGION_SIZE_SHIFT_THRESHOLD,
  ZEE_INTERNAL_ENGINE_STABILITY_VERSION,
  ZEE_INTERNAL_ENGINE_SUPPORTED_FORMATS,
  ZEE_INTERNAL_ENGINE_VERSION,
};
