export const CANONICAL_SIGNATURE_ALGORITHM = 'RS256';
export const CANONICAL_SIGNATURE_KEY_ID = 'chatpdm-vision-signature-v1';
export const CANONICAL_SIGNATURE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvfUatMGuEVOHKNm4gInh
BJFy42WijETv0LQas1W4M2ayyg1OByBUCqIz5p+GLMq1fcpGbnYE99/AevmWmk+Q
pxCH/1NCQyLoavcqE4Im9RJI9zVy0SzQ/Tian/fR+dGFJDC0YUKeggu8DOyFSWHF
ODOOAgLiOvhB3CXVPCaaQjXuhtFlspzaCyjq9DFTifHXuxUzqrhu1RDr1I4rDQMe
J1mxL3WeppKJMxUP6Qil9q3h4yNXV/8PXmISzLxQ2gIxNlgnqjrO2quhOYXnCIWr
mmq5GUY/H9F3fxA6fXqSaQlxvg4kuWjBMFM2ycx6cvGnTq1Kq6AfMi1BHY32E5Un
CwIDAQAB
-----END PUBLIC KEY-----`;
