export const CANONICAL_SIGNATURE_ALGORITHM = 'RS256';
export const CANONICAL_SIGNATURE_KEY_ID = 'chatpdm-vision-signature-v1';
export const CANONICAL_SIGNATURE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsOiKV94HuRbBwXCFpMWO
ecAXA/9ixhGaPS29JDXRXzX7+9m8f3q8/pvXknnr5WbkaZBDRp6X5aWSX57EZc3k
DNrXcYoZnntDCSV8fWIZCpTgKdEEG951tgwsDPbI0dZ6Q5hx3qAezz1rVkTOkfHh
4IdNy9/fWmZVL1i0BgLUQcWo0mWFb1s+JJ/i4dog/EmseMIJsvkji+KxPE886c8r
oE2jGB2zK7OM7ael/uBtRJO8eVzXTPvy/hOcbBdBc7zytEjns1BYKUxlJ3HYR3uU
Yr2ZUvBghM1pq4F0E+rd3TSziH8uMTaSFhhsMP2NrxJQS0KQpg5QMSx7xpRP9H+j
FQIDAQAB
-----END PUBLIC KEY-----`;
