'use strict';

const path = require('node:path');

const MANAGED_ACCESS_ASSURANCE_HASH_VERSION = 1;
const MANAGED_ACCESS_ASSURANCE_CANONICALIZATION_VERSION = 'managed_access_provisioning_evidence.v1';
const MANAGED_ACCESS_ASSURANCE_ANCHOR_SNAPSHOT_SCHEMA_VERSION = 1;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PAYLOAD_SCHEMA_VERSION = 1;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNATURE_SCHEMA_VERSION = 1;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNATURE_ALGORITHM = 'ed25519';
const DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY = path.resolve(
  __dirname,
  '../../../../.cache/managed-access-assurance/anchors',
);
const MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY = process.env.MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY
  ? path.resolve(process.env.MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY)
  : DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY;
const DEFAULT_MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY = path.resolve(
  __dirname,
  '../../../../.cache/managed-access-assurance/checkpoints',
);
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY = process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY
  ? path.resolve(process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY)
  : DEFAULT_MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID =
  process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID || null;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PRIVATE_KEY_PEM =
  process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PRIVATE_KEY_PEM || null;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PUBLIC_KEY_PEM =
  process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PUBLIC_KEY_PEM || null;
const CHECKPOINT_PUBLIC_KEY_LOAD_RESULT = loadManagedAccessAssuranceCheckpointPublicKeys();
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS = Object.freeze(
  CHECKPOINT_PUBLIC_KEY_LOAD_RESULT.publicKeys,
);
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_STATUS =
  CHECKPOINT_PUBLIC_KEY_LOAD_RESULT.status;
const MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_REASON =
  CHECKPOINT_PUBLIC_KEY_LOAD_RESULT.reason;

function loadManagedAccessAssuranceCheckpointPublicKeys() {
  const publicKeys = {};
  let status = 'valid';
  let reason = null;

  if (process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_JSON) {
    try {
      const parsedPublicKeys = JSON.parse(
        process.env.MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_JSON,
      );

      if (parsedPublicKeys && typeof parsedPublicKeys === 'object' && !Array.isArray(parsedPublicKeys)) {
        for (const [keyId, publicKeyPem] of Object.entries(parsedPublicKeys)) {
          if (
            typeof keyId === 'string'
            && keyId.length > 0
            && typeof publicKeyPem === 'string'
            && publicKeyPem.length > 0
          ) {
            publicKeys[keyId] = publicKeyPem;
          }
        }
      } else {
        status = 'invalid';
        reason = 'checkpoint_key_registry_config_invalid';
      }
    } catch (error) {
      status = 'invalid';
      reason = 'checkpoint_key_registry_config_invalid';
    }
  }

  if (
    MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID
    && MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PUBLIC_KEY_PEM
    && !Object.prototype.hasOwnProperty.call(
      publicKeys,
      MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID,
    )
  ) {
    publicKeys[MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID] =
      MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PUBLIC_KEY_PEM;
  }

  return {
    publicKeys,
    status,
    reason,
  };
}

module.exports = Object.freeze({
  DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY,
  DEFAULT_MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY,
  MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY,
  MANAGED_ACCESS_ASSURANCE_ANCHOR_SNAPSHOT_SCHEMA_VERSION,
  MANAGED_ACCESS_ASSURANCE_CANONICALIZATION_VERSION,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_DIRECTORY,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PAYLOAD_SCHEMA_VERSION,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_REASON,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_PUBLIC_KEYS_STATUS,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNATURE_ALGORITHM,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNATURE_SCHEMA_VERSION,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_KEY_ID,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PRIVATE_KEY_PEM,
  MANAGED_ACCESS_ASSURANCE_CHECKPOINT_SIGNING_PUBLIC_KEY_PEM,
  MANAGED_ACCESS_ASSURANCE_HASH_VERSION,
});
