'use strict';

const path = require('node:path');

const MANAGED_ACCESS_ASSURANCE_HASH_VERSION = 1;
const MANAGED_ACCESS_ASSURANCE_CANONICALIZATION_VERSION = 'managed_access_provisioning_evidence.v1';
const MANAGED_ACCESS_ASSURANCE_ANCHOR_SNAPSHOT_SCHEMA_VERSION = 1;
const DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY = path.resolve(
  __dirname,
  '../../../../.cache/managed-access-assurance/anchors',
);
const MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY = process.env.MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY
  ? path.resolve(process.env.MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY)
  : DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY;

module.exports = Object.freeze({
  DEFAULT_MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY,
  MANAGED_ACCESS_ASSURANCE_ANCHOR_DIRECTORY,
  MANAGED_ACCESS_ASSURANCE_ANCHOR_SNAPSHOT_SCHEMA_VERSION,
  MANAGED_ACCESS_ASSURANCE_CANONICALIZATION_VERSION,
  MANAGED_ACCESS_ASSURANCE_HASH_VERSION,
});
