'use strict';

const REASON_CODES = Object.freeze({
  MISSING_REGISTER: 'MISSING_REGISTER',
  MISSING_ZONE: 'MISSING_ZONE',
  EMPTY_TEXT: 'EMPTY_TEXT',
  EXACT_EQUAL: 'EXACT_EQUAL',
  NORMALIZED_EQUAL: 'NORMALIZED_EQUAL',
  PREFIX_ONLY_MUTATION: 'PREFIX_ONLY_MUTATION',
  TOO_CLOSE_TOKEN_OVERLAP: 'TOO_CLOSE_TOKEN_OVERLAP',
  TOO_CLOSE_SENTENCE_SHAPE: 'TOO_CLOSE_SENTENCE_SHAPE',
  STANDARD_TOO_SIMPLE: 'STANDARD_TOO_SIMPLE',
  STANDARD_TOO_FORMAL: 'STANDARD_TOO_FORMAL',
  STANDARD_COLLAPSES_WITH_OTHER_REGISTERS: 'STANDARD_COLLAPSES_WITH_OTHER_REGISTERS',
  STANDARD_REQUIRED_FOR_EXPOSURE: 'STANDARD_REQUIRED_FOR_EXPOSURE',
  STANDARD_PROFILE_NOT_INTERMEDIATE: 'STANDARD_PROFILE_NOT_INTERMEDIATE',
  STANDARD_PROFILE_DRIFT: 'STANDARD_PROFILE_DRIFT',
  SIMPLIFIED_TOO_LONG: 'SIMPLIFIED_TOO_LONG',
  SIMPLIFIED_BANNED_TERM: 'SIMPLIFIED_BANNED_TERM',
  SIMPLIFIED_TOO_CLOSE_TO_STANDARD: 'SIMPLIFIED_TOO_CLOSE_TO_STANDARD',
  SIMPLIFIED_PROFILE_NOT_SIMPLER: 'SIMPLIFIED_PROFILE_NOT_SIMPLER',
  SIMPLIFIED_PROFILE_DRIFT: 'SIMPLIFIED_PROFILE_DRIFT',
  FORMAL_TOO_SHORT: 'FORMAL_TOO_SHORT',
  FORMAL_TOO_CASUAL: 'FORMAL_TOO_CASUAL',
  FORMAL_MISSING_SCOPE_LANGUAGE: 'FORMAL_MISSING_SCOPE_LANGUAGE',
  FORMAL_MISSING_BOUNDARY_LANGUAGE: 'FORMAL_MISSING_BOUNDARY_LANGUAGE',
  FORMAL_TOO_CLOSE_TO_STANDARD: 'FORMAL_TOO_CLOSE_TO_STANDARD',
  FORMAL_PROFILE_NOT_MORE_FORMAL: 'FORMAL_PROFILE_NOT_MORE_FORMAL',
  FORMAL_PROFILE_DRIFT: 'FORMAL_PROFILE_DRIFT',
  BORDERLINE_TOKEN_OVERLAP: 'BORDERLINE_TOKEN_OVERLAP',
  BORDERLINE_SENTENCE_LENGTH: 'BORDERLINE_SENTENCE_LENGTH',
});

module.exports = {
  REASON_CODES,
};
