import type { NormalizationTransformKind } from './normalization.types.ts';

const MAX_TRANSFORM_DEPTH = 3;
const MAX_INPUT_BYTES = 8192;
const MAX_OUTPUT_BYTES = 16384;
const MAX_EXPANSION_RATIO = 4.0;

const NORMALIZATION_PREVIEW_CHARS = 32;
const NORMALIZATION_BASE64_MIN_LENGTH = 4;
const NORMALIZATION_HEX_MIN_LENGTH = 4;

const NORMALIZATION_BASE64_ALLOWED_PATTERN = /^[A-Za-z0-9+/=]+$/;
const NORMALIZATION_BASE64_MARKER_PATTERN = /[A-Z+/=]/;
const NORMALIZATION_BASE64_TRAILING_PADDING_PATTERN = /=+$/;
const NORMALIZATION_HEX_ALLOWED_PATTERN = /^[0-9A-Fa-f]+$/;
const NORMALIZATION_HEX_MARKER_PATTERN = /\d/;

const NORMALIZATION_TRANSFORM_ORDER: readonly NormalizationTransformKind[] = Object.freeze([
  'surface_cleanup',
  'unicode_nfc',
  'percent_decode',
  'base64_decode',
  'hex_decode',
  'reverse_then_base64_decode',
  'reverse_then_hex_decode',
]);

module.exports = {
  MAX_TRANSFORM_DEPTH,
  MAX_INPUT_BYTES,
  MAX_OUTPUT_BYTES,
  MAX_EXPANSION_RATIO,
  NORMALIZATION_PREVIEW_CHARS,
  NORMALIZATION_BASE64_MIN_LENGTH,
  NORMALIZATION_HEX_MIN_LENGTH,
  NORMALIZATION_BASE64_ALLOWED_PATTERN,
  NORMALIZATION_BASE64_MARKER_PATTERN,
  NORMALIZATION_BASE64_TRAILING_PADDING_PATTERN,
  NORMALIZATION_HEX_ALLOWED_PATTERN,
  NORMALIZATION_HEX_MARKER_PATTERN,
  NORMALIZATION_TRANSFORM_ORDER,
};

