import type { SeoRegistryFamily } from '../seo.types';

export const seoStaticEntries = {
  'static.home': {
    title: 'ChatPDM | Answers That Don’t Change or Guess',
    description:
      'ChatPDM is a deterministic reasoning system, not Product Data Management software. Source-backed answers, explicit refusal, and stable concept boundaries.',
    canonicalPath: '/',
    includeInSitemap: true,
    sitemapChangeFrequency: 'weekly',
    sitemapPriority: 1,
    structuredData: {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: 'ChatPDM',
      alternateName: 'Chat PDM',
      url: 'https://chatpdm.com/',
      description:
        'ChatPDM is a deterministic reasoning system, not Product Data Management software. Source-backed answers, explicit refusal, and stable concept boundaries.',
    },
  },
  'static.about': {
    title: 'About ChatPDM - Deterministic Meaning System',
    description: 'Read the product boundary, deterministic posture, and authored-scope model behind the public ChatPDM system.',
    canonicalPath: '/about',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.7,
  },
  'static.what-is-chatpdm': {
    title: 'What Is ChatPDM? - ChatPDM',
    description: 'Learn what ChatPDM is: a deterministic reasoning system, not Product Data Management software or a CAD workflow tool.',
    canonicalPath: '/what-is-chatpdm',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.72,
  },
  'static.zeroglare': {
    title: 'Zeroglare - ChatPDM',
    description: 'ChatPDM\'s internal signal-discipline layer for noise suppression, ambiguity surfacing, and pre-resolution clarity.',
    canonicalPath: '/zeroglare',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.71,
  },
  'static.runtime': {
    title: 'Runtime - ChatPDM',
    description: 'Query the live ChatPDM runtime, inspect reviewed but not-yet-live concepts, and observe bounded refusal behavior directly.',
    canonicalPath: '/runtime',
    includeInSitemap: true,
    sitemapChangeFrequency: 'weekly',
    sitemapPriority: 0.8,
  },
  'static.live-concepts': {
    title: 'Live Concepts - ChatPDM',
    description: 'Inspect the concepts currently admitted to the ChatPDM public runtime without querying them individually.',
    canonicalPath: '/live-concepts',
    includeInSitemap: true,
    sitemapChangeFrequency: 'weekly',
    sitemapPriority: 0.75,
  },
  'static.controlled-comparisons': {
    title: 'Controlled Comparisons - ChatPDM',
    description: 'Inspect the comparison pairs currently admitted to the ChatPDM public runtime and see which conceptual distinctions are allowlisted.',
    canonicalPath: '/controlled-comparisons',
    includeInSitemap: true,
    sitemapChangeFrequency: 'weekly',
    sitemapPriority: 0.74,
  },
  'static.how-it-works': {
    title: 'How ChatPDM Works - Deterministic Answer Model',
    description: 'See how ChatPDM normalizes queries, resolves authored concepts, and refuses unsupported compositions honestly.',
    canonicalPath: '/how-it-works',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.7,
  },
  'static.vision': {
    title: 'Vision - ChatPDM',
    description: 'Read the long-term direction behind ChatPDM: deterministic meaning infrastructure that expands only through proof.',
    canonicalPath: '/vision',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.7,
  },
  'static.reasoning-structure': {
    title: 'Reasoning Structure - ChatPDM',
    description: 'Inspect the deterministic-first reasoning architecture behind ChatPDM and the bounded future layers that may exist only in subordinate roles.',
    canonicalPath: '/reasoning-structure',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.69,
  },
  'static.contact': {
    title: 'Contact - ChatPDM',
    description: 'Follow the public contact route for product, research, and implementation questions as the ChatPDM beta expands.',
    canonicalPath: '/contact',
    includeInSitemap: true,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.4,
  },
  'static.sources': {
    title: 'Sources - ChatPDM',
    description: 'ChatPDM reference sources and canonical grounding.',
    canonicalPath: '/sources',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.5,
  },
  'static.method': {
    title: 'Method - ChatPDM',
    description: 'ChatPDM method and authored scope boundaries.',
    canonicalPath: '/method',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.5,
  },
} satisfies SeoRegistryFamily;
