import type { SeoRegistryFamily } from '../seo.types';

export const seoLegalEntries = {
  'legal.inspect': {
    title: 'Inspect - ChatPDM',
    description: 'Raw inspect entry for ChatPDM policy-backed behavior surfaces.',
    canonicalPath: '/inspect',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.privacy': {
    title: 'Privacy Policy - ChatPDM',
    description: 'Human-readable privacy page placeholder for the current ChatPDM legal surface.',
    canonicalPath: '/privacy',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.privacy.inspect': {
    title: 'Privacy Policy (Inspect) - ChatPDM',
    description: 'Current inspectable privacy surface for ChatPDM implementation behavior and policy traceability.',
    canonicalPath: '/inspect/privacy',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.terms': {
    title: 'Terms of Service - ChatPDM',
    description: 'Human-readable terms surface for the current ChatPDM modeled behavior and boundary rules.',
    canonicalPath: '/terms',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.terms.inspect': {
    title: 'Terms of Service (Inspect) - ChatPDM',
    description: 'Current inspectable terms surface for ChatPDM implementation behavior and allowed-use boundaries.',
    canonicalPath: '/inspect/terms',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies': {
    title: 'Cookie Policy - ChatPDM',
    description: 'Human-readable cookie surface for current essential SSR and browser cookie behavior.',
    canonicalPath: '/cookies',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies.inspect': {
    title: 'Cookie Policy (Inspect) - ChatPDM',
    description: 'Current inspectable cookie surface for ChatPDM browser and SSR implementation behavior.',
    canonicalPath: '/inspect/cookies',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.1,
  },
  'legal.acceptable-use': {
    title: 'Acceptable Use - ChatPDM',
    description: 'ChatPDM acceptable use policy.',
    canonicalPath: '/acceptable-use',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.disclaimer': {
    title: 'Disclaimer - ChatPDM',
    description: 'ChatPDM product disclaimer and usage boundary.',
    canonicalPath: '/disclaimer',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
} satisfies SeoRegistryFamily;
