import type { SeoRegistryFamily } from '../seo.types';

export const seoLegalEntries = {
  'legal.inspect': {
    title: 'Inspect - ChatPDM',
    description: 'Raw inspect entry for ChatPDM policy-backed behavior surfaces.',
    canonicalPath: '/inspect',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.privacy': {
    title: 'Privacy Policy - ChatPDM',
    description: 'Readable privacy policy for the current ChatPDM runtime, covering feedback-linked records, browser session continuity, and internal request transport.',
    canonicalPath: '/privacy',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.privacy.inspect': {
    title: 'Privacy Policy (Inspect) - ChatPDM',
    description: 'Current inspectable privacy surface for ChatPDM implementation behavior and policy traceability.',
    canonicalPath: '/inspect/privacy',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.terms': {
    title: 'Terms of Service - ChatPDM',
    description: 'Human-readable terms shell for current ChatPDM service boundaries and modeled behavior.',
    canonicalPath: '/terms',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.terms.inspect': {
    title: 'Terms of Service (Inspect) - ChatPDM',
    description: 'Current inspectable terms surface for ChatPDM implementation behavior and allowed-use boundaries.',
    canonicalPath: '/inspect/terms',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies': {
    title: 'Cookie Policy - ChatPDM',
    description: 'Canonical cookie policy route redirects to the inspect-backed cookie surface.',
    canonicalPath: '/inspect/cookies',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies.inspect': {
    title: 'Cookie Policy (Inspect) - ChatPDM',
    description: 'Current inspectable cookie surface for ChatPDM browser and SSR implementation behavior.',
    canonicalPath: '/inspect/cookies',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.1,
  },
  'legal.acceptable-use': {
    title: 'Acceptable Use Policy - ChatPDM',
    description: 'Human-readable acceptable use shell for current ChatPDM rule boundaries.',
    canonicalPath: '/acceptable-use',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.acceptable-use.inspect': {
    title: 'Acceptable Use Policy (Inspect) - ChatPDM',
    description: 'Inspectable acceptable-use surface for ChatPDM verification boundaries, refusal paths, and review gates.',
    canonicalPath: '/inspect/acceptable-use',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.1,
  },
  'legal.data-retention': {
    title: 'Data Retention / Data Usage - ChatPDM',
    description: 'Human-readable data retention and data usage shell for ChatPDM.',
    canonicalPath: '/data-retention',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.data-retention.inspect': {
    title: 'Data Retention / Data Usage (Inspect) - ChatPDM',
    description: 'Inspectable data retention and data usage surface for ChatPDM lifecycle, storage, and expiry behavior.',
    canonicalPath: '/inspect/data-retention',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.1,
  },
  'legal.disclaimer': {
    title: 'Disclaimer - ChatPDM',
    description: 'ChatPDM product disclaimer and usage boundary.',
    canonicalPath: '/disclaimer',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
} satisfies SeoRegistryFamily;
