import type { SeoRegistryFamily } from '../seo.types';

export const seoLegalEntries = {
  'legal.inspect': {
    title: 'System Integrity Surface - ChatPDM',
    description: 'Public system integrity surface for registry-backed policy claims, refusal boundaries, and implementation evidence.',
    canonicalPath: '/inspect',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.privacy': {
    title: 'Privacy Policy - ChatPDM',
    description: 'Human-readable privacy page placeholder for the current ChatPDM legal surface.',
    canonicalPath: '/privacy',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.privacy.inspect': {
    title: 'Privacy Policy (Inspect) - ChatPDM',
    description: 'Current inspectable privacy surface for ChatPDM implementation behavior and policy traceability.',
    canonicalPath: '/inspect/privacy',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.data-retention': {
    title: 'Data Retention / Data Usage - ChatPDM',
    description: 'Implementation-backed view over current ChatPDM lifecycle, storage, and expiry behavior.',
    canonicalPath: '/data-retention',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.data-retention.inspect': {
    title: 'Data Retention / Data Usage (Inspect) - ChatPDM',
    description: 'Current inspectable data-retention surface for ChatPDM lifecycle, storage, and expiry evidence.',
    canonicalPath: '/inspect/data-retention',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.terms': {
    title: 'Terms of Service - ChatPDM',
    description: 'Human-readable terms summary for the current ChatPDM beta usage boundary and policy posture.',
    canonicalPath: '/terms',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.terms.inspect': {
    title: 'Terms of Service (Inspect) - ChatPDM',
    description: 'Current inspectable terms surface for ChatPDM runtime operations, field rules, and refusal boundaries.',
    canonicalPath: '/inspect/terms',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies': {
    title: 'Cookie Policy - ChatPDM',
    description: 'Human-readable cookie summary for the current ChatPDM beta and its bounded SSR cookie handling.',
    canonicalPath: '/cookies',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.cookies.inspect': {
    title: 'Cookie Policy (Inspect) - ChatPDM',
    description: 'Current inspectable cookie surface for ChatPDM browser and SSR implementation behavior.',
    canonicalPath: '/inspect/cookies',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.1,
  },
  'legal.acceptable-use': {
    title: 'Acceptable Use - ChatPDM',
    description: 'Implementation-backed view over current ChatPDM runtime scope, refusal boundaries, and feedback-surface constraints.',
    canonicalPath: '/acceptable-use',
    includeInSitemap: true,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.3,
  },
  'legal.acceptable-use.inspect': {
    title: 'Acceptable Use (Inspect) - ChatPDM',
    description: 'Current inspectable acceptable-use surface for ChatPDM runtime scope, refusal behavior, and feedback boundary evidence.',
    canonicalPath: '/inspect/acceptable-use',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
  'legal.disclaimer': {
    title: 'Disclaimer - ChatPDM',
    description: 'ChatPDM product disclaimer and usage boundary.',
    canonicalPath: '/disclaimer',
    includeInSitemap: false,
    sitemapChangeFrequency: 'yearly',
    sitemapPriority: 0.2,
  },
} satisfies SeoRegistryFamily;
