import type { SeoRegistryFamily } from '../seo.types';

export const seoHandbookEntries = {
  'handbooks.index': {
    title: 'Handbooks - ChatPDM',
    description: 'Operational guides for working with ChatPDM safely without breaking deterministic structure, refusal behavior, or separation.',
    canonicalPath: '/handbooks',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.5,
  },
  'handbooks.concept-authoring': {
    title: 'Concept Authoring Handbook - ChatPDM',
    description: 'Operational guide route for defining concepts without collapse and preserving structural boundaries in ChatPDM.',
    canonicalPath: '/handbooks/concept-authoring',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.48,
  },
  'handbooks.review-admission': {
    title: 'Review And Admission Handbook - ChatPDM',
    description: 'Operational guide route for reviewing, validating, and admitting work into ChatPDM without weakening structural discipline.',
    canonicalPath: '/handbooks/review-admission',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.48,
  },
  'handbooks.source-usage': {
    title: 'Source Usage Handbook - ChatPDM',
    description: 'Operational guide route for using sources as structured evidence without allowing them to bypass authored concept discipline.',
    canonicalPath: '/handbooks/source-usage',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.48,
  },
  'handbooks.rejection-handling': {
    title: 'Rejection Handling Handbook - ChatPDM',
    description: 'Operational guide route for documenting and preserving structural rejection without weakening system clarity.',
    canonicalPath: '/handbooks/rejection-handling',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.47,
  },
  'handbooks.comparison-authoring': {
    title: 'Comparison Authoring Handbook - ChatPDM',
    description: 'Operational guide route for authoring allowed comparisons without weakening structural distinction or runtime trust.',
    canonicalPath: '/handbooks/comparison-authoring',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.47,
  },
  'handbooks.runtime-discipline': {
    title: 'Runtime Discipline Handbook - ChatPDM',
    description: 'Operational guide route for preserving refusal behavior, scope discipline, and runtime integrity during change.',
    canonicalPath: '/handbooks/runtime-discipline',
    includeInSitemap: false,
    sitemapChangeFrequency: 'monthly',
    sitemapPriority: 0.47,
  },
} satisfies SeoRegistryFamily;
